### ISSUE TITLE
Inertia with third-party Vue ( or React ) components

### ISSUE THREAD

**Issue by EasyLOB** [inertiajs/inertia-laravel#341] opened 2022-01-02 18:29 UTC
Hi,
I read your documentation about using Laravel + Inertia + Vue ( or React ), but I still have one question.
May I use third-party Vue components like these below ?

Syncfusion
https://www.syncfusion.com/vue-ui-components

Telerik
https://www.telerik.com/kendo-vue-ui

I understand that they use, by default, client-side code and API calls.
So I expect there are changes to made.

Thanks

**Comment by NickSdot** [comment] 2022-01-03 17:12
Yes, there will be changes to be made to make it the Inertia way. But you most likley would need to do this anyway to make the components work with your API/backend.

---

Since this issue is not a bug report, do you maybe want close it to make the maintainers no extra work? :-) The following two channels are available for any kind of questions:

https://github.com/inertiajs/inertia/discussions
https://discord.gg/inertiajs

**Closed** 2022-01-04 16:06 UTC
