### ISSUE TITLE
Reset data-page

### ISSUE THREAD

**Issue by dima-bzz** [inertiajs/inertia-laravel#321] opened 2021-11-20 10:52 UTC
Hi. How reset data-page when logout?

**Comment by ajnsn** [comment] 2021-11-23 10:48
Hey @dima-bzz 
[This](https://github.com/inertiajs/inertia/discussions/780#discussioncomment-1281237) might be an answer or at least an existing discussion about this topic.

**Comment by claudiodekker** [comment] 2021-12-01 22:20
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

Thanks!

(Also, thanks @ajnsn!)

**Closed by claudiodekker** 2021-12-01 22:20 UTC
