### ISSUE TITLE
when using inertia-link JavaScript charts/button/links not working it is working once page refreshed

### ISSUE THREAD

**Issue by ClickerVinod** [inertiajs/inertia-laravel#268] opened 2021-05-24 02:35 UTC
Hi I am using Laravel 8 with Inertiajs, vue3 with Metronic 8 admin theme. when I am using inertia-link JavaScript charts/button/links not working it is working one page refreshed JS charts woks and button also work plz help where I am wrong

My Package.json
`{
"private": true,
"name": "vue-3",
"description": "Laravel Inertia Bs5 and Vue3 App",
"scripts": {
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "prod": "npm run production",
    "production": "mix --production"
},
"devDependencies": {
    "@inertiajs/inertia": "^0.8.4",
    "@inertiajs/inertia-vue3": "^0.3.5",
    "@inertiajs/progress": "^0.2.4",
    "@kirschbaum-development/laravel-translations-loader": "^1.3.2",
    "@tailwindcss/forms": "^0.2.1",
    "@tailwindcss/typography": "^0.3.0",
    "@vue/compiler-sfc": "^3.0.5",
    "@vue/server-renderer": "^3.0.11",
    "alpinejs": "^2.7.3",
    "axios": "^0.21",
    "browser-sync": "^2.26.14",
    "browser-sync-webpack-plugin": "^2.3.0",
    "laravel-echo": "^1.10.0",
    "laravel-mix": "^6.0.19",
    "lodash": "^4.17.19",
    "path-browserify": "^1.0.1",
    "postcss": "^8.1.14",
    "postcss-import": "^12.0.1",
    "pusher-js": "^7.0.3",
    "tailwindcss": "^2.0.1",
    "v-offline": "^1.3.0",
    "vue": "^3.0.5",
    "vue-i18n": "^9.1.6",
    "vue-loader": "^16.1.2",
    "vue3-geolocation": "^1.0.0"
},
"dependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "googlemaps-vue3": "^2.0.4",
    "vue2-google-maps": "^0.10.7",
    "vue3-google-map": "^0.7.9"
}`

my app.js
`require('./bootstrap');
// Import modules...
import { createApp, h, Vue } from 'vue';
import { App as InertiaApp, plugin as InertiaPlugin } from '@inertiajs/inertia-vue3';    
const el = document.getElementById('app');
const app = createApp({});

createApp({
    render: () =>
        h(InertiaApp, {
            initialPage: JSON.parse(el.dataset.page),
            return require(`./Pages/${name}`).default
                      }),
})
.mixin({ methods: { route } })
.use(InertiaPlugin)
.mount(el);`

**Comment by ClickerVinod** [comment] 2021-05-24 11:46
I fixed some part
by using Persistent layouts


i have added  "layout: (h, page) => h(Layout, [page]), "  to all pages /component  this fixed my problem 
but it is only working  if i using 
` resolveComponent: name => require(`@/Pages/${name}`).default,`

but not working if i use
`resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),`

my .babelrc file
`{
    "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
`
my  webpack.config.js
`const path = require('path');
module.exports = {
    resolve: {
        alias: {
             vue$: 'vue/dist/vue.runtime.esm.js',
            '@': path.resolve('resources/js'),
            ziggy: path.resolve('vendor/tightenco/ziggy/dist'),
        },
    },
    output: {
         chunkFilename: 'js/[name].js?id=[chunkhash]',
    },
};
`

this is how  i cahnaged all pages
` <template>
  <layout>
    <h1>Welcome</h1>
  </layout>
</template>

<script>
import Layout from "./Layout";
export default {
  components: {
    Layout,
  },

  layout: (h, page) => h(Layout, [page]), // this line i have added to all pages 
};
</script>

<style>
</style>
`

**Comment by Daronspence** [comment] 2021-09-09 18:31
Is this still an issue @ClickerVinod ?

**Comment by ClickerVinod** [comment] 2021-11-15 13:29
@daronspence thanks for replying  iam strugling for 6 months to fix the issue i have also discussed with theme creators see this link

https://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469/comments?page=543&filter=all#comment_27522968


How i can re init javascript bundle on each inertia response/navigation

plz help me .

**Comment by claudiodekker** [comment] 2021-12-02 22:29
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

-  If you're not sure how or where to get started with Inertia, I can highly recommend Laracasts's incredible (free!) video series: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js

- If you're simply not sure on how to do a certain thing or are running into a problem specific to your application, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-02 22:29 UTC
