### ISSUE TITLE
TS2305: Module '"@inertiajs/inertia-react"' has no exported member

### ISSUE THREAD

**Issue by olivertembo** [inertiajs/inertia-laravel#324] opened 2021-11-26 11:14 UTC
TS2305: Module '"@inertiajs/inertia-react"' has no exported member 'createInertiaApp'

**Comment by claudiodekker** [comment] 2021-12-01 22:18
Duplicate of https://github.com/inertiajs/inertia/issues/980

**Closed by claudiodekker** 2021-12-01 22:18 UTC
