### ISSUE TITLE
Browser cache makes browser display raw Inertia requests

### ISSUE THREAD

**Issue by innocenzi** [inertiajs/inertia-laravel#197] opened 2020-12-15 21:52 UTC
When we do an XHR request which has the same URL as a normal HTML page, and if this XHR request is cached, the browser will display it instead of the HTML page we would expect. 

Inertia works this way: when using an `inertia-link` or a `visit`, an XHR request is made to the same URL we would use to navigate normally, which leads to this: 

![](https://i.imgur.com/eA8huss.gif)

**What happens in this GIF**:
- I load an Inertia-powered application (on production, using Apache, with default `.htaccess` and no custom caching)
- I navigate to another page, using an `inertia-link`
- I navigate out of the app using a bookmark link
- I use the browser back button to go back to the application

In this case, the browser loads what it thinks is the page from the cache, but it actually loads the last XHR request to this URL, which makes it display the raw JSON.

I used the following snippet in the Inertia middleware to disable caching on Inertia responses: 

```php
public function handle(Request $request, Closure $next)
{
    return tap(parent::handle($request, $next), function (Response $response) {
        if ($response->headers->has('X-Inertia')) {
            $response->setCache([
                'no_store' => true,
            ]);
        }
    });
}
```

But it feels like a workaround. Moreover, I can't seem to be able to reproduce this on PingCRM (but I suspect it is because it is in debug mode).

**Comment by RobertBoes** [comment] 2020-12-16 10:41
The default (`Cache-Control: no-cache, private`) seems to be set by Symfony https://github.com/symfony/http-foundation/blob/5.x/ResponseHeaderBag.php#L271. I've set `APP_ENV=production` and `APP_DEBUG=false`, but this seems to have no effect on those headers, so I suspect you're adding the headers somewhere, perhaps in a middleware or apache/nginx config. There's also a php ini setting (cache.cache_limiter), but that should be overwritten by Laravel/Symfony.

I think it would be a good idea to make Inertia's response configurable, although I don't know if it would be easy to implement. It would be nice to configure Inertia in the same way that Jetstream is configured, something like this:
```php
// For fresh page loads, this can be cached
Inertia::configureResponseUsing(function (Response $response) {
  return $response->setCache([
    'private' => true,
    'max_age' => 86400,
  ]);
});

// For X-Inertia responses (xhr) you might want to never cache these
Inertia::configureInertiaResponseUsing(function (Response $response) {
  return $response->setCache([
    'no_cache' => true,
    'private' => true,
  ]);
});
```

**Comment by innocenzi** [comment] 2020-12-16 10:57
Yes, the default HTTP cache strategy is set by Symfony. But the deployed application was using Laravel's default `.htaccess`, and nothing related to the cache was edited.

> I think it would be a good idea to make Inertia's response configurable

It already is, as seen in the snippet I've shown. You can hook onto the `handle` method of the Inertia middleware and tap on the response. I'm not a fan of the Jetstream way to configure stuff, but a method on the default middleware may be useful.

I will (or someone else if they want) investigate the cache stuff and if I end up determining it's something done by default and is messing up Inertia responses, I'll probably PR Inertia with the fix. 

cc @mgkprod

**Comment by claudiodekker** [comment] 2020-12-26 15:05
Hey @innocenzi, is there a chance you could send me a link of an environment or page on which this issue/behaviour still occurs? I'd love to look into it, but after looking at the site you're showing in the gif everything appears to be functional?

**Comment by innocenzi** [comment] 2020-12-26 18:15
@claudiodekker We fixed the previous site, but here is a project which has the issue: https://textgrid.mgk.dev/

1. Open the site
2. Try to log in with anything (just to trigger a visit)
3. Open an external link (eg. with a bookmark)
4. Go back with the browser
5. See: https://i.imgur.com/WlmFv2K.png

**Comment by claudiodekker** [comment] 2020-12-26 19:53
Thanks! I could definitely reproduce this, and your assumption seems correct. 

The only thing I'm worried about implementation-wise, is that some (older?) browsers apparently also show this behaviour when applying `no-store`, meaning we'd probably need to also add `no-cache` at the same time to fully mitigate this?

**Comment by innocenzi** [comment] 2020-12-26 21:32
From what I gathered, it doesn't apply to browser history, which includes the browser back button: https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.13

But I could have misunderstood, and it may need testing. Did you stumble upon a browser for which `no-store` wasn't enough?

**Comment by claudiodekker** [comment] 2020-12-27 17:39
Yeah, you're absolutely right, but in reality some browsers (like certain versions of IE & Firefox) decided to interpret/implement it differently. This at some point even caused the 'recommended' Cache Control stack to be `no-cache, no-store, max-age=0, must-revalidate`

Anyway, even though your solution appears to be a valid one, I still wanted to know what caused this to begin with, and I believe I have found the culprit: For some reason, **your application's back-end (Inertia) response isn't setting the `Vary: Accept` header**: https://github.com/inertiajs/inertia-laravel/blob/master/src/Response.php#L93-L98

This header is used to prevent this exact issue where the last request gets cached when multiple content-types are presented on the same exact endpoint. In case you're curious, here's some more information on it: https://stackoverflow.com/questions/1465974/content-negotiation-ignored-when-using-browser-back-button

I still think it's a good idea to add the `no-cache` and `no-store` headers to make Inertia more robust under these circumstances, so I'll leave the issue open, but I believe that figuring out why this header is being stripped and solving that should fix your issue 👍

**Comment by innocenzi** [comment] 2020-12-28 11:45
I didn't know about `Vary`, that's interesting, thanks. Indeed, I can see `Vary` in the PingCRM demo but not in Magenta Database nor TextGrid. @mgkprod, do you have any idea why?

**Comment by reinink** [comment] 2020-12-28 18:36
Yeah, the `Vary: Accept` header is the key that makes Inertia.js work. Without it, it would be game over.

**Comment by irsyadadl** [comment] 2021-08-21 16:35
How about now ? I'm facing the problem too.

**Comment by claudiodekker** [comment] 2021-12-02 12:59
Hey 👋,

I'm going to close this issue, because this likely ended up being related to the `Vary: Accept` header, as well as that there was no follow-up response from @mgkprod / @innocenzi.
 
If you feel absolutely certain that your issue still points out a bug in the library, and have a reproducable sample in which the `Vary: Accept` header is being used, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-02 12:59 UTC
Labels: bug, enhancement, wontfix
