### ISSUE TITLE
[Suggestion] Fail Inertia Render when component file doesn't exist

### ISSUE THREAD

**Issue by tonysm** [inertiajs/inertia-laravel#195] opened 2020-12-07 14:41 UTC
Laravel fails when we return a view component that doesn't exist (blade), so I thought we could do the same on Inertia::render. Would make sure that at least the page components exist when you hit that route on tests.

**Comment by tonysm** [comment] 2020-12-07 14:44
Uhm, I guess it only makes sense in development/testing mode? Because of the production bundling phase.

**Comment by reinink** [comment] 2020-12-07 23:59
Yeah, the issue is that we don't necessary know where the components are, since the loading of them is handled by JavaScript. We could, however, obviously create a testing helper for this. I wonder if that's something @claudiodekker could build into his Inertia Laravel testing library. 🤔

**Comment by tonysm** [comment] 2020-12-08 12:20
We could have a guesser that's based on the documentation and allow implementing a custom guesser (in the same way that Laravel does with the new database factories). As well as the component extension being used (`.vue`, `.js`, `.jsx`, etc.)

This could be opt-in, of course. Something we could configure in the app middleware or a config file (even though there is no config file for the inertia-laravel package yet.)

**Comment by claudiodekker** [comment] 2020-12-26 12:05
> Yeah, the issue is that we don't necessary know where the components are, since the loading of them is handled by JavaScript. We could, however, obviously create a testing helper for this. I wonder if that's something @claudiodekker could build into his Inertia Laravel testing library. 🤔

Just to make sure I'm correctly understanding this, you mean to test/check against the existence of the file in the application structure, right?

**Comment by reinink** [comment] 2020-12-26 12:22
@claudiodekker Yeah, exactly.

**Comment by claudiodekker** [comment] 2020-12-26 19:51
Yeah, that actually sounds like a very good feature! 

I've created an issue, and will track progress there. Since this means that there will probably be no further activity on this issue here, I'll close this for now 👍

**Closed by claudiodekker** 2020-12-26 19:51 UTC
