### ISSUE TITLE
Data object reactivity issue in redirect 

### ISSUE THREAD

**Issue by atefrihane** [inertiajs/inertia-laravel#306] opened 2021-09-30 11:53 UTC
Hi everyone,
I'm submitting a form which redirects me back to the same page.
The props are updating correctly but the data object is not though..
it only updates on hard refresh..

This is my code

**Home Page** :
```
    public function showDashboard()
    {
        return Inertia::render('Community/ShowDashboard', [
            'latestView' => $this->views->latestView(),
            'views' => $this->views->fetch('all'),
            'filters' => $this->filters->fetch('all'),
        ]);

    }
```

**Submitting form** 

```
   submitView() {
      this.form.post(
        `view/create`,

        {
          preserveScroll: true,

          onSuccess: () => {
            if (this.$page.props.flash.success) {
              swal.fire({
                title: "Success!",
                text: this.$page.props.flash.success,
                icon: "success",
                confirmButtonText: "Close",
              });
            }
          },
          onError: () => {
            let error = "";
            if (this.$page.props.errors.name) {
              error = this.$page.props.errors.name;
            }

            swal.fire({
              title: "Oups!!",
              text: error,
              icon: "error",
              confirmButtonText: "Close",
            });
          },
        }
      );
    },
```

```
   public function handleCreateView(CreateView $request)
    {

        $this->views->store($request->validated());
        return Redirect::back()->with('success', 'View created!');

    }
```
Props and data in component
```
     props: ["latestView", "views", "filters"],

  data() {
    return {
      viewToEdit: false,
      selectedView: this.latestView,
      selectedViewName: this.latestView ? this.latestView.name : "No name",
      query: null,
    };
  },
```
The **selectedView** attribute never gets updated on redirect while it does when I do a hard refresh even though props are updating..

Why this is happening ?

Thanks!

**Comment by claudiodekker** [comment] 2021-12-01 22:42
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

-  If you're not sure how or where to get started with Inertia, I can highly recommend Laracasts's incredible (free!) video series: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js

- If you're simply not sure on how to do a certain thing or are running into a problem specific to your application, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-01 22:42 UTC
