### ISSUE TITLE
Redirect to Intended Url

### ISSUE THREAD

**Issue by muarachmann** [inertiajs/inertia-laravel#245] opened 2021-04-04 21:21 UTC
Hello all, I have been using inertiaJS for a while now and I wish to say thank you for such package. 

I noticed that the default laravel redirect to intended doesn't work as it use to with inertia routes. When i do a full reload it works as expected but the other way round no.

#### Scenario
I have a page **inbox** which I show to authenticated users but I choose to show it on some sidebar. Now on click `<inertia-link :href="route('inbox')">Inbox</inertia-link>`, it redirects me to **login** which is normal and also an Inertia Response but upon authenticating, it takes me to the default intended url **dashboard** in this case and not **inbox**. I expected it to work under the hood or is there some extra stuff I need to do.

Thanks.

**Comment by reinink** [comment] 2021-04-05 10:19
So Inertia shouldn't impact the default Laravel redirect to intended behaviour, and from my testing, this still works as expected. I rely on this behaviour in my own apps.

You can see this in our Ping CRM demo app, by visiting https://demo.inertiajs.com/users, which will redirect you to login, and after login bring you to the users page.

Meaning, I *think* this might be an issue in your app. I'm going to close this for now, but if you're able to track down the issue, and it turns out to be an Inertia related issue, please report back. 👍

**Comment by muarachmann** [comment] 2021-04-05 14:56
Hi @reinink thanks for your reply. Actually your use case is what I explained maybe I dint do it well, when i manually paste an authenticated route in the browser url it works as intended. However say you have a button on the home page **dashboard** which is an inertia link `<inertia-link :href="route('dashboard')">Dashboard</inertia-link>` When the homepage renders, if you click on this link it notices you are not authenticated and takes you to `/login` which also returns an inertia response. After a successful authentication it doesn't take you back to `/dashboard` but rather the default intended redirect route `/home`. 

I hope I explained it a bit clearly reason why I think the issue might be coming from inertia. I think it however losses track of the `url.intended` session  which is needed for redirect

**Comment by muarachmann** [comment] 2021-04-05 14:58
So this happens when you are trying to access an authenticated route using inertia-link. Another usecase is when the session is expired.

**Comment by reinink** [comment] 2021-04-05 19:48
Cool, thanks for the info. I've reopened this, and will test it when I have a moment. 👍

**Comment by hendrikhaack** [comment] 2021-04-05 20:48
In my own app this didn't work too, like discribed by you @muarachmann. 
I ended up customizing my `authenticated` function in my `LoginController` like something following:

```php
protected function authenticated(Request $request, $user): \Illuminate\Http\RedirectResponse
{
    if ($intendetUrl = session()->get('url.intended')) {
        return redirect($intendetUrl);
    }

    return redirect(RouteServiceProvider::HOME);
}
```

**Comment by claudiodekker** [comment] 2021-12-26 12:53
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

Specifically, as already described by @reinink before, Inertia observes Laravel's behaviour. When a redirect to the login occurs due to session expiration, as well as when the user signs in, it is up to Laravel to 'determine' where to send the user to next. Because Inertia sign-ins follow (multiple) redirects until an Inertia response is occurred, this means that this most likely isn't an Inertia issue but instead something you simply want to 'catch' and adjust on the Laravel side of your app.

In either case, if you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-26 12:53 UTC
