### ISSUE TITLE
Active Link

### ISSUE THREAD

**Issue by SeyramWood** [inertiajs/inertia-laravel#259] opened 2021-04-26 22:52 UTC
```
I got this working for me but I stand for modification, thanks.

<li
    :class="`header__nav__list__item ${
    activePage === '/dashboard' ? 'active-left' : ''
  `}`"`
>
 beforeMount() {
//this get the current page url on page reload
    this.activePage = this.$page.url;

//this get the current page url on page naviagate
    Inertia.on("navigate", (event) => {
      this.activePage = event.detail.page.url;
    });
  },
data() {
    return {
      activePage: "",
    };
  },
```

_Originally posted by @SeyramWood in https://github.com/inertiajs/inertia/discussions/75#discussioncomment-662068_

**Comment by ClickerVinod** [comment] 2021-05-24 02:41
hi i use this clear way for active link hope it will help u
use this package in laravel project  [tightenco/ziggy](https://github.com/tighten/ziggy)
`   <inertia-link
              href="/administer/notifications"
              class="menu-link"
              :class="route().current('admin.notifications') ? 'active' : ''"
            >
              <span class="menu-icon">
                <i class="bi bi-app-indicator fs-3"></i>
              </span>
              <span class="menu-title"> {{ $t("tran.notification", 1) }}</span>
            </inertia-link>`

**Comment by claudiodekker** [comment] 2021-12-02 22:32
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

-  If you're not sure how or where to get started with Inertia, I can highly recommend Laracasts's incredible (free!) video series: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js

- If you're simply not sure on how to do a certain thing or are running into a problem specific to your application, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-02 22:32 UTC
