### ISSUE TITLE
InertiaJs sometimes test fails

### ISSUE THREAD

**Issue by jechazelle** [inertiajs/inertia-laravel#292] opened 2021-08-12 06:38 UTC
Hi,

When I run the InertiaJs tests, sometimes test fails. I don't update my code, juste run again. The others test (no Inertia test) run without problem.

```
<?php

namespace Tests\Feature\Dashboard\View;

use App\Models\Company;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Inertia\Testing\Assert;
use Tests\TestCase;

class CompanyTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp();

        $this->company1 = Company::factory()->create([
            'name' => 'Red'
        ]);
        $this->company2 = Company::factory()->create([
            'name' => 'Honey'
        ]);

        $this->user = User::factory()->create([
            'company_id' => $this->company2->id
        ]);
    }

    /**
     *
     */
    public function test_can_view_companies()
    {
        $this->actingAs($this->user)
            ->get('/dashboard/entreprises')
            ->assertInertia(fn (Assert $page) => $page
                ->component('Companies/CompaniesIndex')
                ->has('companies.data', 2)
                ->has('companies.data.0', fn (Assert $page) => $page
                    ->where('id', $this->company2->id)
                    ->where('name', 'Honey')
                    ->where('address', $this->company2->address)
                    ->where('city', $this->company2->city)
                    ->where('postal_code', $this->company2->postal_code)
                    ->where('country', $this->company2->country)
                    ->where('phone_number', $this->company2->phone_number)
                    ->where('email', $this->company2->email)
                    ->where('is_active', $this->company2->is_active)
                    ->where('users_count', 1)
                    ->etc()
                    ->has('users', 1)
                )
            );
    }
}
```

The test fails without information : 

```
 • Tests\Feature\Dashboard\View\CompanyTest > can view companies
  Not a valid Inertia response.

  at vendor/inertiajs/inertia-laravel/src/Testing/Assert.php:80
     76▕             PHPUnit::assertArrayHasKey('props', $page);
     77▕             PHPUnit::assertArrayHasKey('url', $page);
     78▕             PHPUnit::assertArrayHasKey('version', $page);
     79▕         } catch (AssertionFailedError $e) {
  ➜  80▕             PHPUnit::fail('Not a valid Inertia response.');
     81▕         }
     82▕ 
     83▕         return new self($page['component'], $page['props'], $page['url'], $page['version']);
     84▕     }

      +2 vendor frames 
  3   tests/Feature/Dashboard/View/CompanyTest.php:59
      Illuminate\Testing\TestResponse::__call("assertInertia")

```

I tried many things : 

 ##### PhpUnit cache

added cacheResult="false"

##### Added cache:clear and config:clear in CreateApplication.php

```
<?php

namespace Tests;

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\Artisan;

trait CreatesApplication
{
    /**
     * Prepare the test
     */
    public function setUp() : void
    {
        parent::setUp();

        $this->prepareForTests();
    }

    /**
     * Creates the application.
     *
     * @return \Illuminate\Foundation\Application
     */
    public function createApplication()
    {
        $app = require __DIR__.'/../bootstrap/app.php';

        $app->loadEnvironmentFrom('.env.testing');

        $app->make(Kernel::class)->bootstrap();

        return $app;
    }

    /**
     * Migrate the database
     */
    private function prepareForTests()
    {
        Artisan::call('cache:clear');
        Artisan::call('config:clear');
        Artisan::call('migrate:refresh');
        Artisan::call('db:seed --class=CompanySeeder');
        Artisan::call('db:seed --class=UserRoleSeeder');
    }
}

```

I use : 
- inertiajs/inertia-laravel 0.4.4
- Laravel 8.54.0
- @inertiajs/inertia: "^0.10.1"
- @inertiajs/inertia-vue3: "^0.5.2"
- Vue 3

Thank you so much for your help !

#### More informations : 

For example, when I modify the test, add ->dump('companies.data'), I don't see dump just after the run again test. The test fails and I don't see the dump. I launch again and again the test, and after 5 or 6 launch, I see the dump.

And after 5 or 6 launch, test fails again.

In Inertia test, it's like the test doesn't always loaded, it's like a scope doesn't complete load and PhpUnit execute the test on it.

```
->component('Companies/CompaniesIndex')
->dump('companies.data')
->has('companies.data', 2)
```

**Comment by dieg0v** [comment] 2021-09-29 00:09
Hello ... same problem here with  Laravel 8 + Jetstream:

Route:
```php
Route::get('/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');
```

Test:
```php
$user = User::factory()->withPersonalTeam()->create();
$this->actingAs($user);
$response = $this->get('/dashboard');
$response->assertInertia(fn (Assert $inertia) => $inertia
    ->component('Dashboard')
);
```

Error:
```
Not a valid Inertia response.
at vendor/inertiajs/inertia-laravel/src/Testing/Assert.php:80
```

@claudiodekker , in my case,  the problem comes from : 
```
public static function fromTestResponse($response): self
    {
        try {
            $response->assertViewHas('page');
```

Calling **_$response->assertViewHas('page')_** always thrown an error "The response is not a view." because in this Laravel TestResponse method:

```
    protected function responseHasView()
    {
        return isset($this->original) && $this->original instanceof View;
    }
```

**_$this->original_** exists but is always a string ( with html response ),  not a instance of View

Not sure why "original" in response is a string or if is _Inertia::render_ related.

**Comment by ordago** [comment] 2021-10-13 16:40
>Not a valid Inertia response.

I once got this because `beyondcode/laravel-query-detector` was finding N+1 queries and blocking Inertia. I discovered it by inspecting the response in the test.

**Comment by markvesterskov** [comment] 2021-11-10 12:46
> > Not a valid Inertia response.
> 
> I once got this because `beyondcode/laravel-query-detector` was finding N+1 queries and blocking Inertia. I discovered it by inspecting the response in the test.

I had the same issue. Not sure why Query Detector breaks things, but i've removed it and just used Clockwork's built in tools instead.

**Comment by claudiodekker** [comment] 2021-12-23 22:19
Hey,

I'm going close this issue, as it is a duplicate of #290. In addition, as others here already indicate, as well as my closing reply on #290, this issue is likely caused by something else in your application such as a third-party package, custom routing code, custom middleware etc.

In either case, because your issue doesn't contain sufficient information to either reproduce the problem, or to confirm that it's actually an issue with the library, I'm going to close this issue for now. However, if you (or anyone else) has more details (such as an example repository) that allows for reproducing this issue, then please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response, at which point we can re-open this issue.

Thanks!

**Closed by claudiodekker** 2021-12-23 22:19 UTC

**Comment by alazark94** [comment] 2022-08-19 12:58
@claudiodekker this issue occurs when there is a redirect not when a proper `Inertia::render()` is initiated

**Comment by StephenGillCoop** [comment] 2022-08-25 06:39
Just because this is the top response on Google for "Not a valid Inertia Response" I thought I'd reply to this closed thread.

I was getting "Not a valid Inertia response" and couldn't work out why. It ended up being simple - my test was being redirected to the login page which on a vanilla Jetstream app is not considered a valid Inertia response.

Once I added the following, before my code, it worked fine:

```
$this->actingAs(\App\Models\User::factory()->create());
```

**Comment by tomheadifen** [comment] 2022-10-18 04:26
I had this issue because I was passing in the inertia headers `X-Inertia` and `X-Inertia-Version`. When you pass these in you will instead get an object back instead of the inertia view.

**Comment by iraklisg** [comment] 2022-10-26 12:19
Same problem here when using `$response->assertInertia` and `pest`
The tests fail randomly.  :confused:

**Comment by Paxton0222** [comment] 2022-11-29 14:14
In my case, i run `npm run build` script, becase inertia can't found /public/build/manifest.json

**Comment by bsdnomad** [comment] 2023-06-14 15:09
Hi guys,

Just for reference - https://github.com/spatie/laravel-blade-comments/issues/8
In most of the cases it's something away from Inertia, either a third-party library or a faulty component.

**Comment by markvesterskov** [comment] 2024-01-17 14:22
> I'm encountering this too at random with Pest -- it was working just fine with PHPUnit. Did you find a solution?

I cannot recall the exact root cause of the issue, but i remember it not being related to Inertia, but some other middleware causing issues.

**Comment by mreduar** [comment] 2024-01-21 05:15
> > I'm encountering this too at random with Pest -- it was working just fine with PHPUnit. Did you find a solution?
> 
> I cannot recall the exact root cause of the issue, but i remember it not being related to Inertia, but some other middleware causing issues.

I just installed a fresh Laravel project from scratch and doing my first test I get this error. I don't have any specific middleware. I have only installed libraries like laravel pint and phpstan that should not interfere in this process.

**Comment by rdehnhardt** [comment] 2025-03-02 09:40
Just on update on this! 

I recently created a Laravel 12 application using the Inertia + React Starter Kit! The new starter kits have changed the default pages folder from Pages to pages, which causes Inertia.js tests to fail. To fix this, I had to make the following changes:

TestCase.php
```php
<?php

namespace Tests;

use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $this->withoutVite();
    }
}
```

config/inertia.php
```php
<?php

return [

    /**
     * Server Side Rendering
     */
    'ssr' => [
        'enabled' => true,
        'url' => 'http://127.0.0.1:13714',
        // 'bundle' => base_path('bootstrap/ssr/ssr.mjs'),
    ],

    /**
     * Testing
     */
    'testing' => [
        'ensure_pages_exist' => true,
        'page_paths' => [
            resource_path('js/pages'),
        ],
        'page_extensions' => [
            'js',
            'jsx',
            'svelte',
            'ts',
            'tsx',
            'vue',
        ],
    ],

    'history' => [
        'encrypt' => false,
    ],
];
```
