### ISSUE TITLE
Large file size of app.js on server

### ISSUE THREAD

**Issue by afrazahmmad** [inertiajs/inertia-laravel#309] opened 2021-10-06 13:52 UTC
I am working on Laravel Inertia project. app.js on local is 4MB 
When I load the same file on live server then it becomes 13-15MB. due to which page load time increases to 10-15 seconds.

I push file after compressing it by **npm run prod**

Local Response time is few **miliseconds**
https://i.stack.imgur.com/kZzWB.png
Live Response time is **13-40seconds**
https://i.stack.imgur.com/nmLED.png

Everything is working great on local and live except file size issue.
More details in [Stackoverflow question](https://stackoverflow.com/questions/69446503/laravel-inertia-large-file-size-and-long-load-time?noredirect=1#comment122774727_69446503)

**Comment by afrazahmmad** [comment] 2021-11-18 11:42
I have added 
lazy loading and dynamic import 
code splitting but still no change on server

**Comment by claudiodekker** [comment] 2021-12-01 22:38
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

-  If you're not sure how or where to get started with Inertia, I can highly recommend Laracasts's incredible (free!) video series: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js

- If you're simply not sure on how to do a certain thing, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-01 22:38 UTC

**Comment by BroJenuel** [comment] 2022-06-08 00:32
I think what he meant was that the app size is large. I am working with inertiajs. As the system grows larger the size becomes larger as well. How to maybe optimize it so that it only loads needed js.
![image](https://user-images.githubusercontent.com/31676163/172506496-e3a2a9f3-ac26-44c6-9d0e-eeb3946a84d1.png)
