### ISSUE TITLE
Caching requests

### ISSUE THREAD

**Issue by binaryfire** [inertiajs/inertia-laravel#293] opened 2021-08-13 04:45 UTC
Hi guys,

We're considering porting a vanilla Vue3 / Laravel to Inertia. We've implemented API caching in our current app, which improved frontend performance considerably. API requests only hit the db when data has been updated.

Is there a caching strategy we could use with Inertia to achieve the same results?

Cheers

**Comment by claudiodekker** [comment] 2021-12-01 22:45
Hey 👋,

I'm going to close this issue, because it either lacks sufficient explanation regarding your exact problem, how to reproduce said problem, or how the problem relates to a bug or feature with the Inertia library itself.

-  If you're not sure how or where to get started with Inertia, I can highly recommend Laracasts's incredible (free!) video series: https://laracasts.com/series/build-modern-laravel-apps-using-inertia-js

- If you're simply not sure on how to do a certain thing or are running into a problem specific to your application, I recommend you to ask your question in our [Discord](https://discord.com/invite/inertiajs), as a [GitHub Discussions](https://github.com/inertiajs/inertia/discussions) topic, or perhaps even over at [the Laracasts forums](https://laracasts.com/discuss/channels/inertia), as we have a very active community in those places that would be more than happy to help.

If you feel absolutely certain that your issue still points out a bug in the library, please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

Thanks!

**Closed by claudiodekker** 2021-12-01 22:45 UTC
