### ISSUE TITLE
IntertiaJs test show Expected and Actual

### ISSUE THREAD

**Issue by jechazelle** [inertiajs/inertia-laravel#290] opened 2021-08-11 16:32 UTC
First : thank you so much for InertiaJs, it's awesome ! 🙂

I try to execute a simple test with Inertia.
Sometimes I don't see the Expected and Actual, just an error. 
```
--- Expected
  +++ Actual: 
```

My basic test :

```
use Inertia\Testing\Assert;
...
$this->actingAs($this->user)
            ->get('/dashboard/companies')
            ->assertInertia(fn (Assert $page) => $page
                ->component('Companies/CompaniesIndex')
                ->has('companies.data', 2)
                ->has('companies.data.0', fn (Assert $page) => $page
                    ->where('name', 'ok')
                )
            );
```

When it's ok : 

```
  • Tests\Feature\Dashboard\View\CompanyTest > can view companies
  Inertia property [companies.data.0.name] does not match the expected value.
  Failed asserting that two strings are identical.

  at vendor/inertiajs/inertia-laravel/src/Testing/Concerns/Matching.php:49
     45▕ 
     46▕         PHPUnit::assertSame(
     47▕             $expected,
     48▕             $actual,
  ➜  49▕             sprintf('Inertia property [%s] does not match the expected value.', $this->dotPath($key))
     50▕         );
     51▕ 
     52▕         return $this;
     53▕     }

  1   tests/Feature/Dashboard/View/CompanyTest.php:39
      Inertia\Testing\Assert::where("name", "ok")

      +2 vendor frames 
  4   tests/Feature/Dashboard/View/CompanyTest.php:40
      Inertia\Testing\Assert::has("companies.data.0", Object(Closure))
  --- Expected
  +++ Actual
  @@ @@
  -'ok'
  +'Hello Company'

```

And sometimes just an error : 

```
  • Tests\Feature\Dashboard\View\CompanyTest > can view companies
  Not a valid Inertia response.

  at vendor/inertiajs/inertia-laravel/src/Testing/Assert.php:80
     76▕             PHPUnit::assertArrayHasKey('props', $page);
     77▕             PHPUnit::assertArrayHasKey('url', $page);
     78▕             PHPUnit::assertArrayHasKey('version', $page);
     79▕         } catch (AssertionFailedError $e) {
  ➜  80▕             PHPUnit::fail('Not a valid Inertia response.');
     81▕         }
     82▕ 
     83▕         return new self($page['component'], $page['props'], $page['url'], $page['version']);
     84▕     }

      +2 vendor frames 
  3   tests/Feature/Dashboard/View/CompanyTest.php:41
      Illuminate\Testing\TestResponse::__call("assertInertia")

```

I use : 
- inertiajs/inertia-laravel 0.4.4
- Laravel 8.54.0
- @inertiajs/inertia: "^0.10.1"
- @inertiajs/inertia-vue3: "^0.5.2"
- Vue 3

Thank you so much for your help !

**Comment by claudiodekker** [comment] 2021-12-23 22:08
Hey,

From what I can tell, the reason this is failing is unrelated to Inertia itself, and is instead related to either a third-party middleware (throttling, for example?) or something along those lines that causes a non-Inertia response to be returned. 

To make sure this is indeed the case, could you dump the contents of the test response prior to asserting that it is an Inertia response, and repeat this until you hit the error again? Once the error is hit, the output should contain the page, which in turn should tell you more about what's going on.

In either case, because your issue doesn't contain sufficient information to either reproduce the problem, or to confirm that it's actually an issue with the library, I'm going to close this issue for now. However, if you (or anyone else) has more details (such as an example repository) that allows for reproducing this issue, then please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response, at which point we can re-open this issue.

Thanks!

**Closed by claudiodekker** 2021-12-23 22:08 UTC

**Comment by bsdnomad** [comment] 2023-06-14 15:10
> Hey,
> 
> From what I can tell, the reason this is failing is unrelated to Inertia itself, and is instead related to either a third-party middleware (throttling, for example?) or something along those lines that causes a non-Inertia response to be returned.
> 
> To make sure this is indeed the case, could you dump the contents of the test response prior to asserting that it is an Inertia response, and repeat this until you hit the error again? Once the error is hit, the output should contain the page, which in turn should tell you more about what's going on.
> 
> In either case, because your issue doesn't contain sufficient information to either reproduce the problem, or to confirm that it's actually an issue with the library, I'm going to close this issue for now. However, if you (or anyone else) has more details (such as an example repository) that allows for reproducing this issue, then please "@" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response, at which point we can re-open this issue.
> 
> Thanks!

https://github.com/inertiajs/inertia-laravel/issues/292#issuecomment-1591433131
